apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Just some examples of secrets data
  db_user_mgmt_string_connection: c3RyaW5nX2Nvbm5lY3Rpb25fMQ==
  db_agen_mgmt_string_connection: c3RyaW5nX2Nvbm5lY3Rpb25fMg==
  db_subs_mgmt_string_connection: c3RyaW5nX2Nvbm5lY3Rpb25fMw==
